--relacional
DROP TABLE Telefone CASCADE CONSTRAINTS;
DROP TABLE Leitor CASCADE CONSTRAINTS;
DROP TABLE Funcionario CASCADE CONSTRAINTS;
DROP TABLE Secao CASCADE CONSTRAINTS;
DROP TABLE Pessoa CASCADE CONSTRAINTS;
DROP TABLE Logradouro CASCADE CONSTRAINTS;

DROP SEQUENCE seq_id_secao;
DROP SEQUENCE seq_cadastro_funcionario;

DROP TABLE LivroGenero CASCADE CONSTRAINTS;
DROP TABLE LivroAutor CASCADE CONSTRAINTS;
DROP TABLE Autor CASCADE CONSTRAINTS;
DROP TABLE Livro CASCADE CONSTRAINTS;
DROP TABLE LivroInfo CASCADE CONSTRAINTS;
DROP TABLE Permissao CASCADE CONSTRAINTS;

DROP SEQUENCE seq_id_livro;
DROP SEQUENCE seq_id_autor;

DROP TABLE Emprestimo CASCADE CONSTRAINTS;
DROP TABLE Reserva CASCADE CONSTRAINTS;
DROP TABLE Multa CASCADE CONSTRAINTS;

COMMIT;