-- CRIAÇÃO DE TABELAS PARA CADASTRO DE LIVROS

CREATE SEQUENCE seq_id_livro
    START WITH 1
    INCREMENT BY 1;

-- metadados de um livro
-- ISBN é um identificador único para cada edição e variação de um livro publicado comercialmente

CREATE TABLE LivroInfo (
    ISBN VARCHAR2(13),
    Titulo VARCHAR2(100),
    Editora VARCHAR2(50),
    AnoPublicacao INTEGER,
    CONSTRAINT livro_pk PRIMARY KEY (ISBN)
);

-- unidades de um livro
CREATE TABLE Livro (
    ID INTEGER DEFAULT seq_id_livro.NEXTVAL, -- código de tombamento
    ISBN VARCHAR2(13),
    Preco DECIMAL(10, 2),
    CONSTRAINT livro_pk PRIMARY KEY (ID),
    CONSTRAINT livro_fk_info FOREIGN KEY (ISBN) REFERENCES LivroInfo(ISBN)
);

-- Tabela de autores (apenas para armazenar autores)
CREATE TABLE Autor (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nome VARCHAR2(50),
    CONSTRAINT autor_pk PRIMARY KEY (ID)
);

-- Tabela de relacionamento Livro <-> Autor (N:N)
CREATE TABLE LivroAutor (
    ISBN VARCHAR2(13),
    AutorID INTEGER,
    CONSTRAINT livroautor_pk PRIMARY KEY (ISBN, AutorID),
    CONSTRAINT livroautor_fk_livro FOREIGN KEY (ISBN) REFERENCES LivroInfo(ISBN) ON DELETE CASCADE,
    CONSTRAINT livroautor_fk_autor FOREIGN KEY (AutorID) REFERENCES Autor(ID) ON DELETE CASCADE
);